apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-configmap
  namespace: health-monitoring
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/component: microservice
data:
  APP_ENV: "production"
  PORT: "8003"
