prometheusOperator:
  enabled: true

prometheus:
  enabled: true
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: ebs-sc
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1024Mi

alertmanager:
  enabled: true
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: ebs-sc
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi

grafana:
  enabled: true
  adminPassword: "adminpassword123"
  service:
    type: ClusterIP
    port: 80
  persistence:
    enabled: true
    storageClassName: ebs-sc
    size: 5Gi

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true
