apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: health-monitoring
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgrespassword123"
  POSTGRES_DB: "healthdb"
