apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: health-monitoring
  labels:
    app: payment-service
    app.kubernetes.io/name: payment-service
    app.kubernetes.io/component: microservice
spec:
  type: NodePort
  ports:
    - port: 8002
      targetPort: 8002
      name: http
      protocol: TCP
  selector:
    app: payment-service
